apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx-deployment
  namespace: app
  annotations:
    yandex.cloud/load-balancer-type: "external"
  labels:
    app: app-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
      - name: app-nginx
        image: iveisberg/test-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: app-nginx-service
  namespace: app
  labels:
    app: app-nginx
spec:
  selector:
    app: app-nginx
  ports:
  - name: http-web
    nodePort: 30080 # Опционально: можно указать конкретный порт (в диапазоне 30000-32767)
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
